name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: "crpi-ax15wkp071s0xvth.cn-shanghai.personal.cr.aliyuncs.com"
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t crpi-ax15wkp071s0xvth.cn-shanghai.personal.cr.aliyuncs.com/more_peanuts/simplebank:$IMAGE_TAG .
          docker push crpi-ax15wkp071s0xvth.cn-shanghai.personal.cr.aliyuncs.com/more_peanuts/simplebank:$IMAGE_TAG
